# ======================
# Air Configuration
# ======================

root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main.exe ./cmd/server"
bin = "./tmp/main.exe"
full_bin = "./tmp/main.exe"
include_ext = ["go"]
exclude_dir = ["uploads", "tmp"]

[log]
time = true
